from __future__ import annotations

import pytest

from app.github.diff_parser import (
    _build_line_map,
    _should_ignore_file,
    parse_github_pr_files,
)


def test_build_line_map_basic():
    patch = """@@ -1,5 +1,7 @@
 line1
 line2
-line3
+line3_new
+line3_extra
 line4
 line5
"""
    line_map = _build_line_map(patch)
    assert line_map[1] == "line1"
    assert line_map[2] == "line2"
    assert line_map[3] == "line3_new"
    assert line_map[4] == "line3_extra"
    assert line_map[5] == "line4"
    assert line_map[6] == "line5"
    assert 7 not in line_map


def test_build_line_map_with_multiple_hunks():
    patch = """@@ -1,3 +1,4 @@
 a
-b
+b_new
 c
@@ -10,3 +11,4 @@
 x
-y
+y_new
 z
"""
    line_map = _build_line_map(patch)
    assert line_map[1] == "a"
    assert line_map[2] == "b_new"
    assert line_map[3] == "c"
    assert line_map[11] == "x"
    assert line_map[12] == "y_new"
    assert line_map[13] == "z"


def test_should_ignore_lock_files():
    assert _should_ignore_file("package-lock.json", "modified", "patch")
    assert _should_ignore_file("yarn.lock", "modified", "patch")
    assert _should_ignore_file("poetry.lock", "modified", "patch")


def test_should_ignore_dirs():
    assert _should_ignore_file("node_modules/foo/bar.js", "modified", "patch")
    assert _should_ignore_file("dist/bundle.js", "modified", "patch")
    assert _should_ignore_file("vendor/lib.php", "modified", "patch")


def test_should_ignore_binary():
    assert _should_ignore_file("image.png", "modified", "patch")
    assert _should_ignore_file("archive.zip", "modified", "patch")


def test_should_ignore_minified():
    long_line = "x" * 500
    patch = "\n".join([long_line, long_line])
    assert _should_ignore_file("app.min.js", "modified", patch)


def test_should_ignore_generated():
    patch = "# generated by protoc\nx = 1"
    assert _should_ignore_file("service_pb2.py", "modified", patch)


def test_should_not_ignore_source():
    assert not _should_ignore_file("src/main.py", "modified", "@@ -1,1 +1,2 @@\n a\n+b")


def test_parse_github_pr_files_ignores_files():
    files = [
        {"filename": "src/main.py", "status": "modified", "patch": "@@ -1,1 +1,2 @@\n a\n+b", "changes": 1, "additions": 1, "deletions": 0},
        {"filename": "package-lock.json", "status": "modified", "patch": "some json", "changes": 1, "additions": 1, "deletions": 0},
        {"filename": "node_modules/lib.js", "status": "modified", "patch": "code", "changes": 1, "additions": 1, "deletions": 0},
    ]
    parsed, skipped = parse_github_pr_files(files)
    assert len(parsed) == 1
    assert parsed[0].filename == "src/main.py"
    assert len(skipped) == 2


def test_parse_github_pr_files_respects_max_files():
    files = [
        {"filename": f"src/{i}.py", "status": "modified", "patch": "@@ -1,1 +1,2 @@\n a\n+b", "changes": 1, "additions": 1, "deletions": 0}
        for i in range(25)
    ]
    parsed, skipped = parse_github_pr_files(files, max_files=5)
    assert len(parsed) == 5
    assert any("additional files" in reason for reason in skipped)


def test_parse_github_pr_files_respects_char_budget():
    big_patch = "@@ -1,1 +1,2 @@\n" + "\n".join(["x" * 80 for _ in range(8)]) + "\n+y"
    small_patch = "@@ -1,1 +1,2 @@\n a\n+b"
    files = [
        {"filename": "src/big.py", "status": "modified", "patch": big_patch, "changes": 1, "additions": 1, "deletions": 0},
        {"filename": "src/small.py", "status": "modified", "patch": small_patch, "changes": 1, "additions": 1, "deletions": 0},
    ]
    parsed, skipped = parse_github_pr_files(files, max_files=10, max_chars=500)
    assert len(parsed) == 1
    assert parsed[0].filename == "src/small.py"
    assert any("exceeded char budget" in reason for reason in skipped)
