from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

LOCK_FILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    "composer.lock",
    "Gemfile.lock",
    "cargo.lock",
}

IGNORED_DIRS = {"dist", "build", "vendor", "node_modules", ".git", ".github"}

BINARY_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".ico",
    ".svg",
    ".mp4",
    ".mp3",
    ".wav",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".7z",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".bin",
    ".dat",
    ".db",
    ".sqlite",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".otf",
}

GENERATED_PATTERNS = [
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"auto-generated", re.IGNORECASE),
    re.compile(r"do not edit", re.IGNORECASE),
]


@dataclass
class DiffHunk:
    old_start: int
    old_lines: int
    new_start: int
    new_lines: int
    lines: list[tuple[str, str | None]] = field(default_factory=list)
    """List of (line_type, text) where line_type is ' ' (context), '+' (added), '-' (removed)."""


@dataclass
class ParsedFile:
    filename: str
    status: str
    patch: str
    changes: int
    additions: int
    deletions: int
    line_map: dict[int, str] = field(default_factory=dict)
    """Maps new/right-side line number to the diff line content."""

    def right_side_lines(self) -> set[int]:
        return set(self.line_map.keys())


def _is_minified(filename: str, patch: str) -> bool:
    if filename.endswith(".min.js") or filename.endswith(".min.css"):
        return True
    lines = patch.splitlines()
    if not lines:
        return False
    avg = sum(len(line) for line in lines) / max(len(lines), 1)
    return avg > 300


def _is_generated(filename: str, patch: str) -> bool:
    name_lower = filename.lower()
    if ".pb." in name_lower or name_lower.endswith("_pb2.py") or name_lower.endswith("_pb2_grpc.py"):
        return True
    for pattern in GENERATED_PATTERNS:
        if pattern.search(patch[:2000]):
            return True
    return False


def _is_binary(filename: str) -> bool:
    ext = filename[filename.rfind(".") :] if "." in filename else ""
    return ext.lower() in BINARY_EXTENSIONS


def _should_ignore_file(filename: str, status: str, patch: str | None) -> bool:
    if not patch:
        return True
    if status in {"removed", "renamed", "untracked"}:
        return True
    basename = filename.split("/")[-1]
    if basename in LOCK_FILES:
        return True
    parts = filename.split("/")
    if any(part in IGNORED_DIRS for part in parts):
        return True
    if _is_binary(filename):
        return True
    if _is_minified(filename, patch):
        return True
    if _is_generated(filename, patch):
        return True
    return False


def _parse_hunk_header(line: str) -> DiffHunk | None:
    # Example: @@ -1,4 +1,5 @@
    match = re.match(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@", line)
    if not match:
        return None
    old_start = int(match.group(1))
    old_lines = int(match.group(2) or "1")
    new_start = int(match.group(3))
    new_lines = int(match.group(4) or "1")
    return DiffHunk(
        old_start=old_start,
        old_lines=old_lines,
        new_start=new_start,
        new_lines=new_lines,
    )


def _build_line_map(patch: str) -> dict[int, str]:
    """Return a mapping from new/right-side line number to line text."""
    line_map: dict[int, str] = {}
    lines = patch.splitlines()
    new_line: int | None = None

    for raw_line in lines:
        if raw_line.startswith("@@"):
            hunk = _parse_hunk_header(raw_line)
            if hunk is None:
                continue
            new_line = hunk.new_start
            continue

        if new_line is None:
            continue

        if raw_line.startswith("+"):
            line_map[new_line] = raw_line[1:]
            new_line += 1
        elif raw_line.startswith("-"):
            # Removed lines do not appear on the new side.
            continue
        elif raw_line.startswith(" "):
            line_map[new_line] = raw_line[1:]
            new_line += 1
        elif raw_line == "\\ No newline at end of file":
            continue
        else:
            # Treat unknown lines as context for robustness.
            line_map[new_line] = raw_line
            new_line += 1

    return line_map


def parse_github_pr_files(
    files: list[dict[str, Any]], *, max_files: int = 20, max_chars: int = 100_000
) -> tuple[list[ParsedFile], list[str]]:
    """Filter and parse GitHub PR file objects.

    Returns a tuple of (parsed_files, skipped_reasons).
    """
    parsed: list[ParsedFile] = []
    skipped: list[str] = []
    char_budget = max_chars

    for file_obj in files[:max_files]:
        filename = file_obj.get("filename", "")
        status = file_obj.get("status", "")
        patch = file_obj.get("patch")

        if _should_ignore_file(filename, status, patch):
            skipped.append(filename)
            continue

        patch_text = patch or ""
        if len(patch_text) > char_budget:
            skipped.append(f"{filename} (exceeded char budget)")
            continue

        char_budget -= len(patch_text)
        parsed.append(
            ParsedFile(
                filename=filename,
                status=status,
                patch=patch_text,
                changes=file_obj.get("changes", 0),
                additions=file_obj.get("additions", 0),
                deletions=file_obj.get("deletions", 0),
                line_map=_build_line_map(patch_text),
            )
        )

    if len(files) > max_files:
        skipped.append(f"... and {len(files) - max_files} additional files (max_files limit)")

    return parsed, skipped


def get_changed_line_numbers(parsed_file: ParsedFile) -> set[int]:
    """Return new-side line numbers for added lines only."""
    result: set[int] = set()
    new_line: int | None = None
    for raw_line in parsed_file.patch.splitlines():
        if raw_line.startswith("@@"):
            hunk = _parse_hunk_header(raw_line)
            if hunk:
                new_line = hunk.new_start
            continue
        if new_line is None:
            continue
        if raw_line.startswith("+"):
            result.add(new_line)
            new_line += 1
        elif raw_line.startswith("-"):
            continue
        else:
            new_line += 1
    return result


def get_added_lines(parsed_file: ParsedFile) -> list[tuple[int, str]]:
    """Return (new_line_number, text) for every added line."""
    result: list[tuple[int, str]] = []
    new_line: int | None = None
    for raw_line in parsed_file.patch.splitlines():
        if raw_line.startswith("@@"):
            hunk = _parse_hunk_header(raw_line)
            if hunk:
                new_line = hunk.new_start
            continue
        if new_line is None:
            continue
        if raw_line.startswith("+"):
            result.append((new_line, raw_line[1:]))
            new_line += 1
        elif raw_line.startswith("-"):
            continue
        else:
            new_line += 1
    return result
