from __future__ import annotations

import logging
from typing import Any

from app.exceptions import ReviewError
from app.models import Finding, RiskLevel, Severity
from app.review.validator import ValidatedFinding

logger = logging.getLogger(__name__)


def _severity_emoji(severity: Severity) -> str:
    return {
        Severity.critical: "🔴",
        Severity.high: "🟠",
        Severity.medium: "🟡",
        Severity.low: "🟢",
    }.get(severity, "")


def _severity_label(severity: Severity) -> str:
    return severity.value.upper()


def build_review_body(
    summary: str,
    risk_level: RiskLevel,
    findings: list[ValidatedFinding],
    suggested_tests: list[str],
) -> str:
    """Build the markdown body for the PR review."""
    body_lines: list[str] = ["## ReviewPilot AI Review", ""]
    body_lines.append(f"**Risk level:** {risk_level.value.upper()}")
    body_lines.append("")
    body_lines.append("### Summary")
    body_lines.append(summary)
    body_lines.append("")

    # Severity counts from all validated findings.
    counts: dict[Severity, int] = {s: 0 for s in Severity}
    for finding in findings:
        counts[finding.severity] += 1

    body_lines.append("### Findings by severity")
    for severity in (Severity.critical, Severity.high, Severity.medium, Severity.low):
        count = counts[severity]
        emoji = _severity_emoji(severity)
        body_lines.append(f"- {emoji} **{_severity_label(severity)}:** {count}")
    body_lines.append("")

    # Body-only findings (no valid line mapping or duplicate after per-file limit).
    body_findings = [f for f in findings if f.line is None]
    if body_findings:
        body_lines.append("### Findings")
        for finding in body_findings:
            body_lines.extend(_format_finding(finding))
        body_lines.append("")

    if suggested_tests:
        body_lines.append("### Suggested tests")
        for test in suggested_tests:
            body_lines.append(f"- {test}")
        body_lines.append("")

    body_lines.append(
        "---\n*ReviewPilot findings are generated by an AI and should be verified before acting on them.*"
    )
    return "\n".join(body_lines)


def _format_finding(finding: ValidatedFinding | Finding) -> list[str]:
    lines: list[str] = []
    location = f"`{finding.file_path}`"
    if getattr(finding, "line", None):
        location += f":{finding.line}"
    lines.append(
        f"#### {_severity_emoji(finding.severity)} [{_severity_label(finding.severity)}] {finding.title}"
    )
    lines.append(f"**Location:** {location}")
    lines.append(f"**Category:** {finding.category.value}")
    lines.append(f"**Confidence:** {int(finding.confidence * 100)}%")
    lines.append(f"**Explanation:** {finding.explanation}")
    lines.append(f"**Failure scenario:** {finding.failure_scenario}")
    lines.append(f"**Suggestion:** {finding.suggestion}")
    lines.append("")
    return lines


def split_findings_for_review(
    findings: list[ValidatedFinding],
) -> tuple[list[ValidatedFinding], list[dict[str, Any]]]:
    """Split validated findings into body-only list and GitHub review comment dicts."""
    body_findings: list[ValidatedFinding] = []
    comments: list[dict[str, Any]] = []

    for finding in findings:
        if finding.line is None:
            body_findings.append(finding)
            continue

        comments.append(
            {
                "path": finding.file_path,
                "line": finding.line,
                "side": "RIGHT",
                "body": (
                    f"**[{finding.severity.value.upper()}] {finding.title}**\n\n"
                    f"{finding.explanation}\n\n"
                    f"*Failure scenario:* {finding.failure_scenario}\n\n"
                    f"*Suggestion:* {finding.suggestion}"
                ),
            }
        )

    return body_findings, comments


async def publish_review(
    github_client,
    owner: str,
    repo: str,
    pr_number: int,
    review_result: Any,
    validated_findings: list[ValidatedFinding],
) -> dict[str, Any]:
    """Publish a single COMMENT review to GitHub."""
    body = build_review_body(
        review_result.summary,
        review_result.risk_level,
        validated_findings,
        review_result.suggested_tests,
    )
    _, comments = split_findings_for_review(validated_findings)

    logger.info(
        "Publishing review for %s/%s PR #%d with %d inline comments and %d body findings",
        owner,
        repo,
        pr_number,
        len(comments),
        len([f for f in validated_findings if f.line is None]),
    )

    try:
        result = await github_client.create_pull_request_review(
            owner,
            repo,
            pr_number,
            body=body,
            event="COMMENT",
            comments=comments,
        )
    except Exception as exc:
        logger.error("Failed to publish review: %s", type(exc).__name__)
        raise ReviewError("Failed to publish review.") from exc

    return result
